In [2]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [23]:
arr1=np.random.randint(0,101,(3,4))
print(arr1)
#1
np.sort(arr1)

[[ 6 56 34  3]
 [33  6 14 95]
 [36 58 79 82]]


array([[ 3,  6, 34, 56],
       [ 6, 14, 33, 95],
       [36, 58, 79, 82]], dtype=int32)

In [ ]:
'''np.lexsort(arr1[1,::],arr1) '''
#tried using the order parameter of sort() and this also. didnt work
np.argsort(arr1,axis=0)[::,1]
#still cant figure out

array([1, 0, 2])

In [41]:
arr1[np.argsort(arr1[::,1])]

array([[33,  6, 14, 95],
       [ 6, 56, 34,  3],
       [36, 58, 79, 82]], dtype=int32)

In [ ]:
#from stack overflow
#2
arr1[arr1[:, 1].argsort()]

array([[33,  6, 14, 95],
       [ 6, 56, 34,  3],
       [36, 58, 79, 82]], dtype=int32)

In [ ]:
#3
arr1[np.argsort(np.max(arr1,axis=1))][::-1]

array([[33,  6, 14, 95],
       [36, 58, 79, 82],
       [ 6, 56, 34,  3]], dtype=int32)

In [46]:
#4
np.sort(arr1,axis=None).reshape(3,4)

array([[ 3,  6,  6, 14],
       [33, 34, 36, 56],
       [58, 79, 82, 95]], dtype=int32)

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [72]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
extra_subject = np.array([41, 87, 72, 36, 92])
#Two extra students record-
rec1 = np.array([77, 83, 98, 95, 89])
rec2 =np.array([92, 71, 52, 61, 53])

#1
'''marks=np.append(marks,extra_subject.reshape(5,1),axis=1)
marks'''
marks=np.hstack((marks,extra_subject.reshape(5,1)))
marks


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [74]:
#2
marks=np.vstack((marks,rec1,rec2))
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [77]:
#3
marks=np.append(marks,(np.sum(marks,axis=1)).reshape(7,1),axis=1)
marks


array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [ ]:
#4
marks=marks[np.argsort(marks[:,-1])][::-1]
marks[0:2]



array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [ ]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
#col wise                
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

In [ ]:
#row wise
np.unique(arr,axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [90]:
arr=np.arange(0,100).reshape(10,10)
print(arr)
print(np.flip(np.flip(arr,1),0))
print(np.flip(np.flip(arr,0),1))
print(arr[::-1,::-1])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[99 98 97 96 95 94 93 92 91 90]
 [89 88 87 86 85 84 83 82 81 80]
 [79 78 77 76 75 74 73 72 71 70]
 [69 68 67 66 65 64 63 62 61 60]
 [59 58 57 56 55 54 53 52 51 50]
 [49 48 47 46 45 44 43 42 41 40]
 [39 38 37 36 35 34 33 32 31 30]
 [29 28 27 26 25 24 23 22 21 20]
 [19 18 17 16 15 14 13 12 11 10]
 [ 9  8  7  6  5  4  3  2  1  0]]
[[99 98 97 96 95 94 93 92 91 90]
 [89 88 87 86 85 84 83 82 81 80]
 [79 78 77 76 75 74 73 72 71 70]
 [69 68 67 66 65 64 63 62 61 60]
 [59 58 57 56 55 54 53 52 51 50]
 [49 48 47 46 45 44 43 42 41 40]
 [39 38 37 36 35 34 33 32 31 30]
 [29 28 27 26 25 24 23 22 21 20]
 [19 18 17 16 15 14 13 12 11 10]
 [ 9  8  7  6  5  4  3  2  1  0]]
[[99 98

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [105]:
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
x=6
np.unique(np.where(arr>x)[0])

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [110]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,6)
arr3 = np.arange(7,10)
print(arr1,arr2,arr3,end="\n")

[0 1 2] [3 4 5] [7 8 9]


In [113]:
aoa=np.array([arr1,arr2,arr3])
aoa.ravel()

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [115]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [120]:
arr[(arr!=np.min(arr)) & (arr!=np.max(arr))]

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320,
       230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587,
       227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879,
       575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395,
       525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976,
       786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621,
       453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 194, 76

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [6]:
#1
arr=np.random.randint(100,700,(10,10))
arr
arr2=np.clip(arr,100,200)
arr2
#2
np.sort(arr2).cumsum()

array([  130,   322,   518,   718,   918,  1118,  1318,  1518,  1718,
        1918,  2059,  2259,  2459,  2659,  2859,  3059,  3259,  3459,
        3659,  3859,  4059,  4259,  4459,  4659,  4859,  5059,  5259,
        5459,  5659,  5859,  5966,  6074,  6272,  6472,  6672,  6872,
        7072,  7272,  7472,  7672,  7794,  7994,  8194,  8394,  8594,
        8794,  8994,  9194,  9394,  9594,  9704,  9904, 10104, 10304,
       10504, 10704, 10904, 11104, 11304, 11504, 11691, 11883, 12083,
       12283, 12483, 12683, 12883, 13083, 13283, 13483, 13583, 13783,
       13983, 14183, 14383, 14583, 14783, 14983, 15183, 15383, 15583,
       15783, 15983, 16183, 16383, 16583, 16783, 16983, 17183, 17383,
       17520, 17668, 17832, 18032, 18232, 18432, 18632, 18832, 19032,
       19232])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [16]:
#1
arr=np.random.rand(10,100)
print(arr)
arr=np.round(arr,decimals=3)
print(arr)
#2
print(np.percentile(arr,0))
#3
print(np.percentile(arr,100))
#4
print(np.percentile(arr,51)-np.percentile(arr,50))

[[3.90095037e-01 3.92487383e-01 7.84520913e-01 6.39516959e-01
  2.89608480e-01 6.10235472e-01 4.56042756e-01 4.36103604e-01
  1.54196126e-01 1.37989370e-01 7.81793913e-01 1.67301107e-01
  8.34976376e-01 2.57805325e-01 9.91980596e-01 3.15075682e-02
  3.55873859e-01 8.47854963e-01 8.59063062e-01 8.87651085e-01
  6.66421794e-01 6.63893561e-01 2.99844430e-01 8.03494653e-01
  2.21660692e-01 8.73355689e-02 5.51984508e-01 1.61394169e-02
  2.42404275e-01 1.07743093e-01 1.65309802e-01 7.68491160e-01
  3.65876638e-01 1.71711135e-01 5.17159826e-01 8.79812249e-01
  7.18129594e-01 8.32129794e-01 7.47837248e-01 6.36918565e-01
  4.75482239e-01 3.29738076e-01 2.36617859e-01 1.77171201e-01
  2.02148967e-02 5.67428430e-01 9.48751806e-01 7.05468411e-02
  5.12569382e-01 3.70328920e-02 6.33582433e-01 5.30218669e-01
  1.80099245e-03 8.23516264e-01 4.44659051e-01 9.76419707e-01
  1.59204275e-01 5.01020331e-01 6.58422486e-01 2.86022821e-01
  5.01651334e-01 6.12142012e-01 1.95567157e-02 2.92748310e-01
  9.2474